#!/bin/bash

# Error handling
set -o nounset
set -o errexit

# global vars
#folder=`pwd` #if $0 is at root
folder=`cd "$(dirname $0)"; pwd | sed s/\\\/scripts//g` #if $0 is in /scripts

# please adjust to your needs
autocommit=true
version_filename="VERSION.txt"
changelog_filename="CHANGELOG.txt"

# do not touch
version_file="$folder/$version_filename"
version_temp="$folder/.VERSION.txt.new"
changelog_file="$folder/$changelog_filename"
changelog_temp="$folder/.CHANGELOG.txt.new"

# prints usage (when called with help, -h or --help)
usage() {
	echo
	echo "usage: $0 <version> <description of version>"
	echo "  e.g. $0 0.2.0 Added documentation"
	show_current_version
	exit
}

# prints current version
show_current_version() {
	echo
	echo -n "Current version is: "
	if ! [ -w "$version_file" ]; then
		echo " -- no version file, yet --"
	else
		cat $version_file
	fi
}

# updates version file
update_version() {
	if ! echo "$version" > $version_temp; then
		echo "Could not replace VERSION"
		exit 2
	fi
	mv $version_temp $version_file
	echo -n "Bumped version to: "
	cat $version_file
}

# prepends version and description to changelog
update_changelog() {
	if ! [ -w "$changelog_file" ]; then
		touch $changelog_file
	fi
	echo "$version - $description"|cat - $changelog_file > $changelog_temp && mv $changelog_temp $changelog_file
	echo -n "Changelog: "
	head -1 $changelog_file
}

# commit to git
commit() {
	if [ -d "$folder/.git" ]; then
		git reset -q HEAD .
		git add $version_file $changelog_file
		git commit -m "Bumped Version to $version"
		git push
		git tag -a "$version" -m "Bumped Version to $version"
		git push --tags
	fi
}

# prepends description and commits to changelog.md
update_changelog_md() {
entry=<<EOF
Changelog
=========

## :version - :description

* [:sha1] - :commitmsg
EOF
	if ! [ -w "$changelog_md" ]; then
		touch $changelog_md
	fi
	echo "## $version - $description"|cat - $changelog_md > $changelog_temp && mv $changelog_temp $changelog_md
#	echo -n "Changelog: "
#	head -1 $changelog_file
}



# if none or only one argument is given...
if [ $# -lt 2 ]; then

	# ... check, if user needs help
	if [ $# == 1 ]; then
		case $1 in
		    'help') usage;;
		    '-h') usage;;
		    '--help') usage;;
		esac
	fi
	
	# ... or guide him through everything
	show_current_version
	echo -n "Please enter new version: "
	read version
	echo -n "Please enter description: "
	read description
fi

# user is a pro - prepare arguments
if [ $# -ge 2 ]; then
	version=$1
	description=`echo $@ | cut -f2- -d\ `
fi

# do the stuff (make sure, $version and $description are set)
update_version
update_changelog

if $autocommit; then commit fi

#update_changelog_md #unfinished

