#!/bin/bash
# Generates changelog day by day
NEXT=$(date +%F)
echo "# CHANGELOG"
git log --no-merges --format="%cd" --date=short | sort -u -r | while read DATE ; do
    echo
    echo "## $DATE"
    echo
    GIT_PAGER=cat git log --no-merges --format=" * %s" --since=$DATE --until=$NEXT
    NEXT=$DATE
done